version: "3.8"
services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: my-weak-password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Cambié el puerto a 5433
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nestjs.com 
      PGADMIN_DEFAULT_PASSWORD: my-weak-password
      PAGDMIN_LISTEN_PORT: 80
    ports:
      - 8082:80
    volumes:
      - /var/lib/pgadmin
    depends_on:
      - db